steps:
  - label: ':eslint: Lint'
    command: .buildkite/steps/lint.sh
    agents:
      queue: npm-packages
    plugins:
      docker-compose#v2.5.1:
        config: docker-compose.yml
        run: redux_reducers

  - wait

  - label: ':jest: Tests'
    command: .buildkite/steps/test.sh
    agents:
      queue: npm-packages
    plugins:
      docker-compose#v2.5.1:
        config: docker-compose.yml
        run: redux_reducers

  - wait

  - label: ':rocket: publish'
    command: .buildkite/steps/publish.sh
    agents:
      queue: npm-packages
    branches: master
    concurrency: 1
    concurrency_group: 'redux-reducers/publish'
    plugins:
      docker-compose#v2.5.1:
        config: docker-compose.yml
        run: redux_reducers
